#!/usr/bin/env python3
"""
Generate influxdb/manifest.yml (the `influx apply` spec) for the cascading
downsample chain, from a compact tier table. Regenerate instead of hand-editing
12+ near-identical YAML blocks — that hand-editing is what produced the
_measurement/_field filter bug.

What it fixes / adds vs the old hand-written manifest:
  * CORRECT filter: _measurement == "network_interface" AND
    _field in {statistics_out-octets, statistics_in-octets}
    (the old manifest filtered _measurement == "statistics_out-octets", which
    is a FIELD, so every task read nothing and every tier stayed empty).
  * min/max/median in addition to mean. Each aggregate stored as its own field
    suffix (_mean/_min/_max/_median) in the SAME tier bucket, so no point
    collisions. min/max cascade exactly; mean ~exactly; median-of-medians is an
    approximation (acceptable for downsampling — disclose in the paper).

Run:  python3 generate_manifest.py   ->  writes manifest.yml
Then: docker compose up (influx-setup applies it) or `influx apply -f manifest.yml`
"""

RAW_BUCKET = "infldb"
MEASUREMENT = "network_interface"
BASE_FIELDS = ["statistics_out-octets", "statistics_in-octets"]
AGGS = ["mean", "min", "max", "median"]  # suffix == flux aggregate fn name

# Delay each task's execution past the ingestion lag, WITHOUT shifting the
# window it reads: InfluxDB keeps a task's `now()` pinned to its scheduled time
# and only defers when the task actually runs, so `range(start: -task.every)`
# still covers the intended window.
#
# WHY: telegraf.conf sets no flush_interval, so Telegraf batches at its 10s
# default. A task firing exactly on the window boundary therefore reads a
# window whose last few seconds have not been written yet (measured lag
# oscillates ~1.6-7.5s). Every tier point was being computed from a truncated
# window — for the 1m tier, up to ~17% of the window missing, biasing
# mean/min/max/median. Verified by verify_counter_aggregation.py: tier `max`
# consistently sat below the window's true last counter value.
#
# 30s > the observed lag with margin, and stays below the smallest tier's
# 1m `every`.
OFFSET = "30s"

# (tier_name, every, retention_seconds, retention_comment)
TIERS = [
    ("1m",   "1m",   3600,      "floored to InfluxDB 1h minimum (2x rule -> 600s, rejected)"),
    ("5m",   "5m",   7200,      "2h = 2x the 1h consuming task"),
    ("1h",   "1h",   57600,     "16h = 2x the 8h consuming task"),
    ("8h",   "8h",   172800,    "2d = 2x the 1d consuming task"),
    ("1d",   "1d",   1209600,   "2w = 2x the 1w consuming task"),
    ("1w",   "1w",   4838400,   "8w = 2x the 4w consuming task"),
    ("4w",   "4w",   14515200,  "24w = 2x the 12w consuming task"),
    ("12w",  "12w",  29030400,  "48w = 2x the 24w consuming task"),
    ("24w",  "24w",  62899200,  "~2y = 2x the 52w consuming task"),
    ("52w",  "52w",  314496000, "~10y = 2x the 260w consuming task"),
    ("260w", "260w", 628992000, "~20y = 2x the 520w consuming task"),
    ("520w", "520w", 314496000, "~10y terminal tier, no downstream task"),
]

HEADER = """\
# GENERATED by generate_manifest.py — DO NOT hand-edit. Change the tier table
# in the generator and re-run instead.
#
# Cascading downsample chain. Each tier = one Bucket (storage + retention) plus
# one Task (scheduled Flux downsample). Tier N reads tier N-1, applies
# mean/min/max/median over its window, writes suffixed fields (_mean/_min/_max/
# _median) into its bucket.
#
# Retention rule: a tier's retention >= the `every` of the task that reads FROM
# it, or the source expires before consumption. Each below = 2x that interval
# (floored to InfluxDB's 3600s minimum). Init bucket "infldb"
# (DOCKER_INFLUXDB_INIT_BUCKET) is the raw source — not defined here.
"""


def bucket_block(name, every_ret_secs, comment):
    return f"""\
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
  name: traffic-{name}
spec:
  name: traffic-{name}
  description: Traffic metrics at {name} resolution (mean/min/max/median fields).
  retentionRules:
    - type: expire
      everySeconds: {every_ret_secs}   # {comment}
"""


def field_filter(fields):
    return " or ".join(f'r._field == "{f}"' for f in fields)


def tier1_task(name, every):
    """First tier: read raw base fields, emit 4 suffixed aggregates."""
    writes = []
    for agg in AGGS:
        writes.append(
            f"""\
    data
      |> aggregateWindow(every: {every}, fn: {agg}, createEmpty: false)
      |> map(fn: (r) => ({{r with _field: r._field + "_{agg}"}}))
      |> to(bucket: "traffic-{name}")
"""
        )
    body = "\n".join(writes)
    return f"""\
apiVersion: influxdata.com/v2alpha1
kind: Task
metadata:
  name: downsample-raw-to-{name}
spec:
  name: downsample-raw-to-{name}
  description: Downsamples raw {RAW_BUCKET} to {name} mean/min/max/median.
  every: {every}
  offset: {OFFSET}
  query: |

    data = from(bucket: "{RAW_BUCKET}")
      |> range(start: -task.every)
      |> filter(fn: (r) => r._measurement == "{MEASUREMENT}")
      |> filter(fn: (r) => {field_filter(BASE_FIELDS)})

{body}"""


def tierN_task(name, every, prev):
    """Later tiers: read prev tier's suffixed fields, aggregate like-with-like."""
    writes = []
    for agg in AGGS:
        agg_fields = [f"{f}_{agg}" for f in BASE_FIELDS]
        writes.append(
            f"""\
    src
      |> filter(fn: (r) => {field_filter(agg_fields)})
      |> aggregateWindow(every: {every}, fn: {agg}, createEmpty: false)
      |> to(bucket: "traffic-{name}")
"""
        )
    body = "\n".join(writes)
    return f"""\
apiVersion: influxdata.com/v2alpha1
kind: Task
metadata:
  name: downsample-{prev}-to-{name}
spec:
  name: downsample-{prev}-to-{name}
  description: Downsamples the {prev} tier to {name} (mean/min/max/median cascade).
  every: {every}
  offset: {OFFSET}
  query: |

    src = from(bucket: "traffic-{prev}")
      |> range(start: -task.every)
      |> filter(fn: (r) => r._measurement == "{MEASUREMENT}")

{body}"""


def main():
    docs = [HEADER]
    prev = None
    for name, every, ret, comment in TIERS:
        docs.append(bucket_block(name, ret, comment))
        if prev is None:
            docs.append(tier1_task(name, every))
        else:
            docs.append(tierN_task(name, every, prev))
        prev = name
    out = "\n---\n".join(docs)
    with open("manifest.yml", "w") as f:
        f.write(out)
    print(f"Wrote manifest.yml: {len(TIERS)} tiers x (1 bucket + 1 task), "
          f"{len(AGGS)} aggregates each.")


if __name__ == "__main__":
    main()
